import type { Metadata } from "next";
import { Geist, Playwrite_IE } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playwriteIE = Playwrite_IE({
  variable: "--font-playwrite-ie",
  weight: ["100", "200", "300", "400"],
});

export const metadata: Metadata = {
  title: "The Regret Ledger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.className} ${playwriteIE.variable} h-full antialiased`}
    >
      <body>
        <Header />

        <div className="max-w-3xl mx-auto p-5 my-14">{children}</div>
      </body>
    </html>
  );
}
